---
- name: configurando apache2 virtualhost
  hosts: zapatero
  become: true
  vars_files:
    - myvarsfile.yml

  tasks:
  - name: crear directorio
    file:
      path: /var/www/html/departamento
      state: directory
      owner: "{{usuario}}"
      group: "{{usuario}}"

  - name: copiar virtualhost 
    copy: >
      src=files/etc/httpd/sites-available/departamento.conf dest=/etc/httpd/sites-available/departamento.conf mode=0646

  - name: enlace simbolico del virtualhost 
    file:
      src: /etc/httpd/sites-available/departamento.conf
      dest: /etc/httpd/sites-enabled/departamento.conf
      state: link

    notify:
      - restart apache2

  handlers:
    - name: restart apache2
      service: name=httpd state=restarted
