---
- name: Bind9 configuration
  hosts: rajoy
  become: true
  tasks:
    - name: Set cname departamento in luisgn.conf
      lineinfile:
        dest: /var/cache/bind/db.luisgn
        line: 'departamento IN      CNAME zapatero'
      notify:
        - restart bind

  handlers:
    - name: restart bind
      service: name=bind9 state=restarted
