---
- name: Create a ftp default root
  hosts: zapatero
  become: true
  vars_files:
    - myvarsfile.yml

  tasks:
    - name: agregar ruta por defecto del usuario
      lineinfile:
        dest: /etc/proftpd.conf
        line: 'DefaultRoot                     /var/www/html/departamento {{usuario}}'
      notify:
        - restart proftpd

  handlers:
    - name: restart proftpd
      command: systemctl restart proftpd

