---
- name: Create a ftp default root
  hosts: zapatero
  become: true
  vars_files:
    - myvarsfile.yml

  tasks:
  - name: agregar ruta por defecto del usuario
    command: echo DefaultRoot                     /var/www/html/{{usuario}} {{usuario}} >> /etc/proftpd.conf

    notify:
      - restart proftpd

  handlers:
    - name: restart proftpd
      command: systemctl restart proftpd

