---
- name: creating user
  hosts: zapatero
  become: true
  vars_files:
    - myvarsfile.yml

  tasks:
  - name: agregando usuario
    command: useradd -m {{usuario}}

  - name: agregando password -> {{password}}
    user:
      name: '{{ usuario }}'
      password: '{{ password | password_hash("sha512") }}'
      update_password: 'always'
